# Use root/example as user/password credentials
version: "3.1"

services:
  MySQL:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - .env
  Mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env